from __future__ import annotations

import logging
import re
import threading
import time
from dataclasses import dataclass
from html import unescape
from pathlib import Path
from typing import Any
from urllib.parse import urljoin

import requests

from agent.services.api_client import APIClient, Printer

LOGGER = logging.getLogger(__name__)
ADDRESS_DEBUG_LOG_FILE = Path("storage/data/address_list_debug.log")

@dataclass
class AddressEntry:
    type: str
    registration_no: str
    name: str
    user_code: str
    date_last_used: str
    email_address: str
    folder: str
    entry_id: str = ""

class RicohServiceBase:
    def __init__(self, api_client: APIClient, interval_seconds: int = 60) -> None:
        self.api_client = api_client
        self.interval_seconds = interval_seconds
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None
        # Keep a monotonic local hint so address registration_no generated by app always increases.
        self._address_index_hint_by_ip: dict[str, int] = {}

    def _timestamp(self) -> str:
        return time.strftime("%Y-%m-%d %H:%M:%S")

    def _append_address_debug(self, message: str) -> None:
        try:
            ADDRESS_DEBUG_LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
            with ADDRESS_DEBUG_LOG_FILE.open("a", encoding="utf-8") as f:
                f.write(f"{self._timestamp()} {message}\n")
        except Exception as exc:  # noqa: BLE001
            LOGGER.warning("Failed to write address debug log: %s", exc)

    @staticmethod
    def _http_get(url: str, timeout: int = 10, session: requests.Session | None = None) -> str:
        if session:
            resp = session.get(url, timeout=timeout)
        else:
            resp = requests.get(url, timeout=timeout)
        resp.raise_for_status()
        return resp.text

    def _logout_after_collect(self, printer: Printer, source: str = "") -> None:
        logout_url = f"http://{printer.ip}/web/entry/en/websys/webArch/logout.cgi"
        try:
            # We don't bother checking response, typically we just hit it and move on.
            requests.get(logout_url, timeout=5)
            LOGGER.info("Logged out from %s (%s)", printer.name, source)
        except Exception as exc:  # noqa: BLE001
            LOGGER.debug("Logout failed (expected for some models): ip=%s error=%s", printer.ip, exc)

    def _verify_session_state(self, session: requests.Session, printer: Printer, username: str) -> bool:
        """
        Loads a protected administrator-only page to confirm whether we are fully logged in as ADMIN.
        We check two different endpoints to ensure maximum compatibility across firmware versions.
        """
        base_url = f"http://{printer.ip}"
        
        # Endpoint A: Easy Security config (strictly administrator-only)
        try:
            url_a = urljoin(base_url, "/web/entry/en/websys/easySecurity/getEasySecurity.cgi")
            resp_a = session.get(url_a, timeout=5)
            is_login_a = any(ind in resp_a.text for ind in ["authForm.cgi", "login.cgi", "Login User Name", "Login Password"])
            if resp_a.status_code == 200 and not is_login_a:
                LOGGER.info("[RicohLogin] Admin session verified via EasySecurity")
                return True
        except Exception as exc:
            LOGGER.debug("[RicohLogin] EasySecurity verification check failed: %s", exc)

        # Endpoint B: Address user wizard GET (requires write/admin privileges)
        try:
            url_b = urljoin(base_url, "/web/entry/en/address/adrsGetUserWizard.cgi")
            resp_b = session.get(url_b, timeout=5)
            is_login_b = any(ind in resp_b.text for ind in ["authForm.cgi", "login.cgi", "Login User Name", "Login Password"])
            if resp_b.status_code == 200 and not is_login_b:
                LOGGER.info("[RicohLogin] Admin session verified via adrsGetUserWizard")
                return True
        except Exception as exc:
            LOGGER.debug("[RicohLogin] adrsGetUserWizard verification check failed: %s", exc)

        LOGGER.warning("[RicohLogin] Admin session verification failed for %s - session is either guest or unauthenticated", printer.ip)
        return False

    def _login(self, session: requests.Session, printer: Printer, credential_candidates: list[tuple[str, str]] | None = None) -> tuple[str, str]:
        """
        Form-based login to Ricoh copier.
        Returns successfully used (user, password) tuple.
        """
        base_url = f"http://{printer.ip}"
        LOGGER.info("[RicohLogin] Starting login for copier %s (IP: %s)", printer.name, printer.ip)
        
        # Build candidate list
        candidates = []
        if credential_candidates:
            candidates.extend(credential_candidates)
        if printer.user or printer.password:
            candidates.append((printer.user or "", printer.password or ""))
        candidates.extend([("admin", ""), ("admin", "admin")])
        
        seen: set[tuple[str, str]] = set()
        final_candidates: list[tuple[str, str]] = []
        for u, p in candidates:
            if (u, p) not in seen:
                seen.add((u, p))
                final_candidates.append((u, p))

        LOGGER.info("[RicohLogin] Credentials to attempt: %s", [(u, "***" if p else "") for u, p in final_candidates])

        last_exception = None
        for attempt, (user, password) in enumerate(final_candidates):
            LOGGER.info("[RicohLogin] Attempt %d/%d: user=%s", attempt + 1, len(final_candidates), user)

            try:
                session.cookies.clear()
                session.auth = None
                session.cookies.set("cookieOnOffChecker", "on")

                # On first attempt only, release any stale session on the copier
                if attempt == 0:
                    try:
                        session.get(urljoin(base_url, "/web/entry/en/websys/webArch/logout.cgi"), timeout=3)
                    except Exception:
                        pass

                # GET login form to obtain wimToken (single pass)
                form_urls = [
                    "/web/entry/en/websys/webArch/authForm.cgi",
                    "/web/guest/en/websys/webArch/authForm.cgi",
                ]
                wim_token = ""
                referer_url = ""

                for form_path in form_urls:
                    try:
                        url = urljoin(base_url, form_path)
                        LOGGER.info("[RicohLogin] GET %s", form_path)
                        resp = session.get(url, timeout=8)
                        if resp.status_code == 200:
                            html_content = resp.text
                            # Handle JS intermediate redirect if present (same as test_login_226.py)
                            if "document.form1.submit()" in html_content or "name='form1'" in html_content or 'name="form1"' in html_content:
                                LOGGER.info("[RicohLogin] Intermediate redirect form detected. Following POST redirect...")
                                hidden = self._extract_hidden_inputs(html_content)
                                action_match = re.search(r'action\s*=\s*["\']([^"\']+)["\']', html_content, re.IGNORECASE)
                                if action_match:
                                    redirect_url = urljoin(resp.url, action_match.group(1))
                                    LOGGER.info("[RicohLogin] POST Redirect %s", action_match.group(1))
                                    resp = session.post(redirect_url, data=hidden, timeout=8)
                                    html_content = resp.text

                            wim_token = self._extract_wim_token(html_content)
                            if not wim_token:
                                wim_token = self._extract_hidden_inputs(html_content).get("wimToken", "")
                            referer_url = resp.url
                            LOGGER.info("[RicohLogin] Form OK, wimToken=%s", bool(wim_token))
                            break
                    except Exception as e:
                        LOGGER.debug("[RicohLogin] GET %s failed: %s", form_path, e)
                        continue

                if not referer_url:
                    LOGGER.warning("[RicohLogin] Could not load login form for %s", printer.ip)
                    continue

                # POST login (Sequential strategies including Base64 support for new Ricoh models)
                import base64
                encoded_user = base64.b64encode(user.encode()).decode()
                encoded_pass = base64.b64encode(password.encode()).decode()

                strategies = [
                    # Strategy A: Base64 to guest cgi (priority - works on most models)
                    {
                        "name": "Base64 (guest)",
                        "path": "/web/guest/en/websys/webArch/login.cgi",
                        "data": {
                            "userid": encoded_user,
                            "username": encoded_user,
                            "password": encoded_pass,
                            "open": "websys/webArch/authForm.cgi"
                        }
                    },
                    # Strategy B: Plain Text to entry cgi
                    {
                        "name": "Plain (entry)",
                        "path": "/web/entry/en/websys/webArch/login.cgi",
                        "data": {
                            "userid": user,
                            "username": user,
                            "password": password,
                        }
                    },
                    # Strategy C: Plain Text to guest cgi
                    {
                        "name": "Plain (guest)",
                        "path": "/web/guest/en/websys/webArch/login.cgi",
                        "data": {
                            "userid": user,
                            "username": user,
                            "password": password,
                        }
                    },
                ]

                for strategy in strategies:
                    post_url = urljoin(base_url, strategy["path"])
                    data = dict(strategy["data"])
                    if wim_token:
                        data["wimToken"] = wim_token

                    LOGGER.info("[RicohLogin] POST %s using %s Strategy", strategy["path"], strategy["name"])
                    try:
                        resp = session.post(post_url, data=data, headers={"Referer": referer_url}, timeout=8)
                    except Exception as post_exc:
                        LOGGER.debug("[RicohLogin] POST %s failed: %s", strategy["path"], post_exc)
                        continue

                    wim_session = session.cookies.get("wimsesid", "")
                    real_session = bool(wim_session) and wim_session != "--"
                    LOGGER.info("[RicohLogin] POST result using %s: status=%d wimsesid=%s", strategy["name"], resp.status_code, "valid" if real_session else wim_session or "NONE")

                    is_login_page = any(ind in resp.text for ind in ["Login User Name", "Login Password"])
                    is_still_form = "authForm.cgi" in resp.text and ('name="userid"' in resp.text or 'name="username"' in resp.text)

                    if resp.status_code == 200 and not is_login_page and not is_still_form and real_session:
                        if self._verify_session_state(session, printer, user):
                            LOGGER.info("[RicohLogin] Success! Logged in as '%s' via %s (%s)", user, strategy["path"], strategy["name"])
                            printer.user = user
                            printer.password = password
                            return (user, password)
                        else:
                            LOGGER.info("[RicohLogin] POST OK but verify failed")

            except Exception as exc:
                LOGGER.warning("[RicohLogin] Exception: %s", exc)
                last_exception = exc

            if attempt < len(final_candidates) - 1:
                time.sleep(0.5)

        if last_exception:
            raise last_exception
        raise RuntimeError(f"All login attempts failed for {printer.ip}")

    def _login_auth_form_only(self, session: requests.Session, printer: Printer) -> None:
        """Deprecated/Legacy: Use unified _login instead if possible."""
        self._login(session, printer)

    def _reset_web_session(self, session: requests.Session, printer: Printer) -> None:
        base_url = f"http://{printer.ip}"
        # Quick logout - fire and forget
        for path in ["/web/entry/en/websys/webArch/logout.cgi", "/web/guest/en/websys/webArch/logout.cgi"]:
            try:
                session.get(urljoin(base_url, path), timeout=3)
            except Exception:
                continue
        try:
            session.cookies.clear()
        except Exception:
            pass
            return

    def reset_web_session(self, printer: Printer) -> None:
        """
        Public helper used by UI/polling flow to force-clear web session cookies
        on device side without requiring authentication.
        """
        session = requests.Session()
        try:
            self._reset_web_session(session, printer)
        finally:
            try:
                session.close()
            except Exception:  # noqa: BLE001
                pass

    def create_http_client(self, printer: Printer, credential_candidates: list[tuple[str, str]] | None = None, authenticated: bool = True) -> requests.Session:
        """
        Creates a session. If authenticated=True, performs login.
        """
        LOGGER.info("[RicohClient] Creating requests session: IP=%s, authenticated=%s", printer.ip, authenticated)
        session = requests.Session()
        session.headers.update({"User-Agent": "printer-agent/0.1"})
        
        if authenticated:
            self._login(session, printer, credential_candidates=credential_candidates)
        return session

    def create_http_client_auth_form_only(self, printer: Printer) -> requests.Session:
        """Deprecated: Use create_http_client instead."""
        return self.create_http_client(printer, authenticated=True)

    def authenticate_and_get(self, session: requests.Session, printer: Printer, target_url: str) -> str:
        """
        Compatibility layer: Ensures we are logged in and fetches the target.
        """
        url = urljoin(f"http://{printer.ip}", target_url)
        LOGGER.info("[RicohHTTP] GET %s (timeout=15s)", target_url)
        start_time = time.time()
        response = session.get(url, timeout=15)
        elapsed = time.time() - start_time
        LOGGER.info("[RicohHTTP] GET %s -> Status %d (%.2fs, length=%d)", target_url, response.status_code, elapsed, len(response.text))
        response.raise_for_status()
        html = response.text

        # Check if we hit a login page or if our session expired/redirected to guest view
        is_login_page = any(m in html for m in ["authForm.cgi", "login.cgi", "Login User Name", "Login Password"])
        is_admin_page = "/web/entry/" in url
        has_admin_content = any(c in html for c in ["ReportListArea", "adrsList", "adrsGetUser", "adrsSetUser", "adrsDeleteEntries"])
        
        if is_login_page or (is_admin_page and not has_admin_content):
            LOGGER.info("[RicohHTTP] Session expired, guest view, or auth screen encountered for admin URL %s, re-authenticating IP %s...", url, printer.ip)
            self._login(session, printer)
            LOGGER.info("[RicohHTTP] Re-auth complete. Retrying GET %s...", target_url)
            start_time = time.time()
            response = session.get(url, timeout=15)
            elapsed = time.time() - start_time
            LOGGER.info("[RicohHTTP] Retry GET %s -> Status %d (%.2fs, length=%d)", target_url, response.status_code, elapsed, len(response.text))
            response.raise_for_status()
            html = response.text

        return html

    def _extract_wim_token(self, html: str) -> str:
        # Matches: wimToken="value", wimToken='value', wimToken = value, wimToken: "value", wimToken: 'value'
        match = re.search(r'wimToken\s*[:=]\s*["\']?([^"\'\s;>]+)["\']?', html, re.IGNORECASE)
        if match:
            return match.group(1)
        # Matches: name="wimToken" value="value", name='wimToken' value='value', name=wimToken value=value
        match = re.search(r'name\s*=\s*["\']?wimToken["\']?\s+value\s*=\s*["\']?([^"\'\s>]+)["\']?', html, re.IGNORECASE)
        if match:
            return match.group(1)
        # Matches: value="value" name="wimToken", value='value' name='wimToken', value=value name=wimToken
        match = re.search(r'value\s*=\s*["\']?([^"\'\s>]+)["\']?\s+name\s*=\s*["\']?wimToken["\']?', html, re.IGNORECASE)
        return match.group(1) if match else ""

    def _extract_hidden_inputs(self, html: str) -> dict[str, str]:
        """Simple regex extraction of hidden input fields."""
        fields: dict[str, str] = {}
        for match in re.finditer(
            r'<input\s+[^>]*?type\s*=\s*["\']?hidden["\']?[^>]*?>', html, re.IGNORECASE | re.DOTALL
        ):
            tag = match.group(0)
            name_m = re.search(r'name\s*=\s*["\']?([^"\'\s>]+)["\']?', tag, re.IGNORECASE)
            value_m = re.search(r'value\s*=\s*["\']?([^"\'\s>]*)["\']?', tag, re.IGNORECASE)
            if name_m:
                fields[name_m.group(1)] = unescape(value_m.group(1)) if value_m else ""
        
        # Also check for wimToken variable in script or document
        if "wimToken" not in fields or not fields["wimToken"]:
            token = self._extract_wim_token(html)
            if token:
                fields["wimToken"] = token
        return fields

    @staticmethod
    def _strip_html(input_value: str) -> str:
        text = re.sub(r"<[^>]*>", "", input_value)
        text = re.sub(r"\s+", " ", text)
        return unescape(text.strip())

    @staticmethod
    def _pick_field_key(keys: list[str], candidates: list[str]) -> str | None:
        for c in candidates:
            if c in keys:
                return c
            # Case insensitive check
            for k in keys:
                if k.lower() == c.lower():
                    return k
        return None
