server {
    listen 80;
    server_name download.goxprint.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://download.goxprint.com$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name download.goxprint.com;

    ssl_certificate /etc/letsencrypt/live/download.goxprint.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/download.goxprint.com/privkey.pem;

    location ~* ^/(printagent.*\.exe)$ {
        alias /opt/printagent/static/releases/$1;
        default_type application/octet-stream;
        add_header Content-Disposition 'attachment; filename="$1"';
        add_header Access-Control-Allow-Origin * always;
    }

    location / {
        return 301 https://app.goxprint.com/;
    }
}
