import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    paddingBottom: '100px',
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '428px',
    marginLeft: 'auto',
    marginRight: 'auto',
    boxSizing: 'border-box',
    position: 'relative',
  },
  fixedHeader: {
    position: 'fixed',
    top: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: '428px',
    background: 'var(--color-bg)',
    zIndex: 100,
    padding: '16px 14px 8px 14px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    borderBottom: '1px solid var(--color-surface-light)',
  },
  scrollableContent: {
    marginTop: '230px', // Offsets the height of fixedHeader
    padding: '12px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: 'var(--color-primary)',
    margin: 0,
  },
  filterBar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    padding: '10px 12px',
    borderRadius: '10px',
    background: 'color-mix(in srgb, var(--color-primary) 6%, var(--color-surface))',
    border: '1px solid color-mix(in srgb, var(--color-primary) 15%, transparent)',
  },
  filterLabel: {
    fontSize: '0.72rem',
    fontWeight: 600,
    color: 'var(--color-text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  lanSelect: {
    fontSize: '0.82rem',
    padding: '8px 10px',
    background: 'var(--color-bg)',
    color: 'var(--color-text)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '6px',
    cursor: 'pointer',
    width: '100%',
  },
  tabBar: {
    display: 'flex',
    borderBottom: '1px solid var(--color-surface-light)',
  },
  tabBtn: {
    flex: 1,
    padding: '10px 4px',
    fontSize: '0.82rem',
    fontWeight: 700,
    textAlign: 'center',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    transition: 'color var(--anim-fast)',
  },
  tabContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  loadingWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '40px 0',
  },
  emptyText: {
    textAlign: 'center',
    color: 'var(--color-text-secondary)',
    fontSize: '0.8rem',
    padding: '24px 0',
    fontStyle: 'italic',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '8px',
    gap: '8px',
  },
  cardTitle: {
    fontSize: '0.9rem',
    fontWeight: 700,
    color: 'var(--color-text)',
  },
  copierTitle: {
    fontSize: '0.9rem',
    fontWeight: 700,
    color: 'var(--color-primary)',
    display: 'block',
  },
  copierSubtitle: {
    fontSize: '0.72rem',
    color: 'var(--color-text-secondary)',
    marginTop: '2px',
    fontFamily: 'monospace',
  },
  statusBadge: {
    fontSize: '0.65rem',
    fontWeight: 700,
    padding: '1px 6px',
    borderRadius: '4px',
    border: '1px solid',
    flexShrink: 0,
  },
  cardDetails: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    background: 'var(--color-inset-bg)',
    padding: '8px 10px',
    borderRadius: '8px',
    border: '1px solid var(--color-surface-light)',
  },
  detailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '0.78rem',
  },
  detailLabel: {
    color: 'var(--color-text-secondary)',
    fontWeight: 500,
  },
  detailValue: {
    color: 'var(--color-text)',
    fontWeight: 600,
    textAlign: 'right',
  },
  cardActionWrapper: {
    marginTop: '8px',
  },
  sectionBlock: {
    marginTop: '8px',
    padding: '8px',
    background: 'var(--color-inset-bg)',
    borderRadius: '8px',
    border: '1px solid var(--color-surface-light)',
  },
  sectionBlockTitle: {
    fontSize: '0.75rem',
    fontWeight: 700,
    color: 'var(--color-text-secondary)',
    display: 'block',
    marginBottom: '6px',
  },
  credsInputRow: {
    display: 'flex',
    gap: '6px',
  },
  credsInput: {
    fontSize: '0.8rem',
    padding: '6px 8px',
    background: 'var(--color-bg)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '6px',
    flex: 1,
    minWidth: 0,
  },
  relaySelect: {
    fontSize: '0.8rem',
    padding: '4px 6px',
    background: 'var(--color-surface)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '6px',
    cursor: 'pointer',
    flex: 1,
    marginLeft: '12px',
    minWidth: 0,
    color: 'var(--color-text)',
  },
  syncStatusBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 10px',
    borderRadius: '8px',
    border: '1px solid',
    marginTop: '8px',
    gap: '8px',
  },
  syncStatusTitle: {
    fontSize: '0.72rem',
    color: 'var(--color-text-secondary)',
    fontWeight: 600,
    display: 'block',
  },
  syncStatusText: {
    fontSize: '0.75rem',
    marginTop: '2px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  destinationsBlock: {
    marginTop: '10px',
    padding: '10px 8px',
    background: 'var(--color-inset-bg)',
    borderRadius: '8px',
    border: '1px solid var(--color-surface-light)',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  destBlockTitle: {
    fontSize: '0.78rem',
    fontWeight: 700,
    color: 'var(--color-text-secondary)',
    borderBottom: '1px solid var(--color-surface-light)',
    paddingBottom: '4px',
  },
  destItemCard: {
    padding: '8px 10px',
    background: 'var(--color-surface)',
    borderRadius: '6px',
    border: '1px solid var(--color-surface-light)',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  destItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  destItemTitle: {
    fontSize: '0.8rem',
    fontWeight: 700,
    color: 'var(--color-text)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },
  destTypeBadge: {
    fontSize: '0.6rem',
    fontWeight: 800,
    padding: '1px 4px',
    borderRadius: '3px',
  },
  destRegNo: {
    fontSize: '0.7rem',
    color: 'var(--color-text-secondary)',
    fontWeight: 600,
  },
  destPathValue: {
    fontSize: '0.72rem',
    color: 'var(--color-text-secondary)',
    fontFamily: 'monospace',
    wordBreak: 'break-all',
  },
  destStatusBadge: {
    fontSize: '0.62rem',
    fontWeight: 700,
    padding: '1px 5px',
    borderRadius: '3px',
  },
  destRowActions: {
    display: 'flex',
    gap: '4px',
    marginTop: '6px',
    borderTop: '1px solid var(--color-surface-light)',
    paddingTop: '6px',
  },
  destRowBtn: {
    flex: 1,
    padding: '4px 0',
    fontSize: '0.7rem',
    fontWeight: 600,
    textAlign: 'center',
    color: 'var(--color-primary)',
    background: 'rgba(255,255,255,0.02)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  ftpCredentialsBox: {
    marginTop: '4px',
    background: 'var(--color-inset-bg)',
    padding: '4px 6px',
    borderRadius: '4px',
    fontSize: '0.7rem',
    border: '1px solid var(--color-surface-light)',
    color: 'var(--color-text)',
  },
  copyTextBtn: {
    color: 'var(--color-primary)',
    fontSize: '0.65rem',
    fontWeight: 700,
    cursor: 'pointer',
    background: 'none',
    border: 'none',
  },
  expandSubBtn: {
    fontSize: '0.72rem',
    color: 'var(--color-primary)',
    fontWeight: 600,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 0',
    display: 'block',
  },
  suggestedDriverBlock: {
    padding: '8px',
    background: 'var(--color-inset-bg)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  driverSuggestionItem: {
    background: 'var(--color-surface)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '6px',
    overflow: 'hidden',
  },
  driverModelHeader: {
    padding: '6px 8px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    cursor: 'pointer',
    background: 'rgba(255,255,255,0.02)',
  },
  driverOptionsList: {
    padding: '6px',
    borderTop: '1px solid var(--color-surface-light)',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  driverFileRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '4px 6px',
    background: 'var(--color-inset-bg)',
    borderRadius: '4px',
    gap: '6px',
  },
  driverFileName: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  driverFileUrl: {
    fontSize: '0.62rem',
    color: 'var(--color-text-secondary)',
    fontFamily: 'monospace',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  driverDownloadBtn: {
    fontSize: '0.7rem',
    fontWeight: 700,
    color: 'var(--color-primary)',
    padding: '4px 8px',
    borderRadius: '4px',
    background: 'rgba(0, 212, 255, 0.08)',
    border: '1px solid rgba(0, 212, 255, 0.2)',
    whiteSpace: 'nowrap',
  },
  emptySubText: {
    fontSize: '0.72rem',
    color: 'var(--color-text-secondary)',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '8px 0',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.85)',
    zIndex: 150,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  modalCard: {
    backgroundColor: 'var(--color-surface)',
    borderTop: '1px solid var(--color-surface-light)',
    borderTopLeftRadius: '16px',
    borderTopRightRadius: '16px',
    width: '100%',
    maxWidth: '428px',
    maxHeight: '82vh',
    display: 'flex',
    flexDirection: 'column',
    padding: '16px',
    boxSizing: 'border-box',
    boxShadow: '0 -4px 24px rgba(0,0,0,0.3)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '12px',
  },
  modalTitle: {
    fontSize: '0.95rem',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: 0,
  },
  modalSubtitle: {
    fontSize: '0.72rem',
    color: 'var(--color-text-secondary)',
    fontFamily: 'monospace',
    marginTop: '2px',
    wordBreak: 'break-all',
  },
  modalCloseBtn: {
    fontSize: '1.5rem',
    lineHeight: 1,
    cursor: 'pointer',
    color: 'var(--color-text-secondary)',
    background: 'none',
    border: 'none',
    padding: '0 4px',
  },
  modalBody: {
    flex: 1,
    overflowY: 'auto',
    marginBottom: '12px',
  },
  modalLoading: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '30px 0',
  },
  modalFooter: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'flex-end',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    marginBottom: '12px',
  },
  formHelpText: {
    fontSize: '0.68rem',
    color: 'var(--color-text-secondary)',
    marginTop: '2px',
  },
  modalInput: {
    fontSize: '0.85rem',
    padding: '8px 10px',
    background: 'var(--color-bg)',
    color: 'var(--color-text)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '6px',
    width: '100%',
  },
  filesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  fileItemRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 10px',
    background: 'var(--color-inset-bg)',
    borderRadius: '6px',
    border: '1px solid var(--color-surface-light)',
    gap: '8px',
  },
  fileLinkName: {
    fontSize: '0.78rem',
    fontWeight: 700,
    color: 'var(--color-primary)',
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    wordBreak: 'break-all',
  },
  fileMetaDetails: {
    fontSize: '0.68rem',
    color: 'var(--color-text-secondary)',
    marginTop: '2px',
  },
  fileUploadMeta: {
    fontSize: '0.65rem',
    color: 'var(--color-secondary)',
    marginTop: '1px',
    fontWeight: 500,
  },
  fileDownloadBtn: {
    fontSize: '0.72rem',
    fontWeight: 700,
    color: 'var(--color-primary)',
    padding: '5px 10px',
    borderRadius: '4px',
    background: 'rgba(0, 212, 255, 0.08)',
    border: '1px solid rgba(0, 212, 255, 0.2)',
    whiteSpace: 'nowrap',
  },
  modalDetailsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '10px',
    background: 'var(--color-inset-bg)',
    borderRadius: '8px',
    border: '1px solid var(--color-surface-light)',
  },
  toastContainer: {
    position: 'fixed',
    top: '12px',
    right: '12px',
    left: 'auto',
    zIndex: 9999,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '4px',
    width: 'auto',
    maxWidth: 'min(48vw, 240px)',
    pointerEvents: 'none',
  },
  toast: {
    background: 'transparent',
    backdropFilter: 'blur(4px)',
    borderRadius: '4px',
    padding: '3px 8px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    color: 'var(--color-text)',
    pointerEvents: 'auto',
    fontSize: '0.72rem',
    lineHeight: 1.2,
    width: 'auto',
    maxWidth: '100%',
    wordBreak: 'break-word',
  },
  toastIcon: {
    fontSize: '0.75rem',
    flexShrink: 0,
    lineHeight: 1,
  },
  smallBtn: {
    background: 'transparent',
    color: 'var(--color-primary)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '6px',
    padding: '6px 10px',
    fontSize: '0.75rem',
    fontWeight: 500,
    cursor: 'pointer',
    boxSizing: 'border-box',
    display: 'inline-flex',
    alignItems: 'center',
  },
  confirmOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.85)',
    zIndex: 160,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
  },
  confirmModalCard: {
    backgroundColor: 'var(--color-surface)',
    border: '1px solid var(--color-surface-light)',
    borderRadius: '12px',
    width: '90%',
    maxWidth: '360px',
    padding: '16px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
    margin: 'auto',
  },
};
